default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5

development:
  <<: *default
  database: learn_easy_development

test:
  <<: *default
  database: learn_easy_test

production:
  <<: *default
  database: learn_easy_production
  username: learn_easy
  password: <%= ENV['LEARN_EASY_DATABASE_PASSWORD'] %>
